#import <ParseKit/PKSParser.h>

enum {
    MODPKJSON_TOKEN_KIND_OBJECTIDTOKEN = 14,
    MODPKJSON_TOKEN_KIND_COLONTOKEN,
    MODPKJSON_TOKEN_KIND_FALSETOKEN,
    MODPKJSON_TOKEN_KIND_COMMATOKEN,
    MODPKJSON_TOKEN_KIND_OPENBRACKETTOKEN,
    MODPKJSON_TOKEN_KIND_TRUETOKEN,
    MODPKJSON_TOKEN_KIND_OPENCURLYTOKEN,
    MODPKJSON_TOKEN_KIND_UNDEFINEDTOKEN,
    MODPKJSON_TOKEN_KIND_NULLTOKEN,
    MODPKJSON_TOKEN_KIND_CLOSEBRACKETTOKEN,
    MODPKJSON_TOKEN_KIND_OPENPARENTHESETOKEN,
    MODPKJSON_TOKEN_KIND_CLOSECURLYTOKEN,
    MODPKJSON_TOKEN_KIND_CLOSEPARENTHESETOKEN,
};

@interface MODPKJsonParser : PKSParser

@end

